name: Release

on:
  workflow_dispatch:

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.9.0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Zip extensions
        id: zip_extensions
        run: |
          pnpm zip
          pnpm zip:firefox
        # 假设 pnpm zip:firefox 生成两个压缩包：dist/firefox-extension.zip 和 dist/firefox-source.zip
        outputs:
          chrome_zip_path: dist/extension.zip
          firefox_zip_path: dist/firefox-extension.zip
          firefox_source_zip_path: dist/firefox-source.zip

      - name: Get package version
        id: get_version
        run: echo VERSION=$(node -p "require('./package.json').version") >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        with:
          tag_name: bookline-v${{ env.VERSION }}
          release_name: 'bookline v${{ env.VERSION }}'
          body: 'See the assets to download this version and install.'
          draft: false
          prerelease: false

      - name: Upload Chrome extension to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.zip_extensions.outputs.chrome_zip_path }}
          asset_name: chrome-extension-v${{ env.VERSION }}.zip
          asset_content_type: application/zip

      - name: Upload Firefox extension to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.zip_extensions.outputs.firefox_zip_path }}
          asset_name: firefox-extension-v${{ env.VERSION }}.zip
          asset_content_type: application/zip

      - name: Upload Firefox source zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.zip_extensions.outputs.firefox_source_zip_path }}
          asset_name: firefox-source-v${{ env.VERSION }}.zip
          asset_content_type: application/zip
