name: Release

on:
  workflow_dispatch:

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.9.0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Get package version
        id: get_version
        run: echo VERSION=$(node -p "require('./package.json').version") >> $GITHUB_ENV

      - name: Zip extensions
        run: |
          pnpm zip
          pnpm zip:firefox 
          echo "CHROME_ZIP_PATH=.output/bookline-${{ env.VERSION }}-chrome.zip" >> $GITHUB_ENV
          echo "FIREFOX_ZIP_PATH=.output/bookline-${{ env.VERSION }}-firefox.zip" >> $GITHUB_ENV
          echo "FIREFOX_SOURCE_ZIP_PATH=.output/bookline-${{ env.VERSION }}-sources.zip" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        with:
          tag_name: bookline-v${{ env.VERSION }}
          release_name: 'bookline v${{ env.VERSION }}'
          body: 'See the assets to download this version and install.'
          draft: false
          prerelease: false

      - name: Upload Chrome extension to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.CHROME_ZIP_PATH }}
          asset_name: chrome-extension-v${{ env.VERSION }}.zip
          asset_content_type: application/zip

      - name: Upload Firefox extension to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.FIREFOX_ZIP_PATH }}
          asset_name: firefox-extension-v${{ env.VERSION }}.zip
          asset_content_type: application/zip

      - name: Upload Firefox source zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.FIREFOX_SOURCE_ZIP_PATH }}
          asset_name: firefox-source-v${{ env.VERSION }}.zip
          asset_content_type: application/zip
