name: Release

on:
  workflow_dispatch:

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.9.0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Zip extensions
        run: |
          pnpm zip
          pnpm zip:firefox

      - name: Get package version
        id: get_version
        run: echo VERSION=$(node -p "require('./package.json').version") >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        with:
          tagName: bookline-v${{ env.VERSION }} # 使用环境变量替换 __VERSION__
          releaseName: 'bookline v${{ env.VERSION }}'
          releaseBody: 'See the assets to download this version and install.'
          draft: false
          prerelease: false

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: browser-extensions
          path: |
            .output/*.zip
             ${{ steps.create_release.outputs.upload_url }}
